export const types = {
    GET_INSTITUTION_LIST: 'GET_INSTITUTION_LIST',
    REQUEST_GET_INSTITUTION_LIST: 'REQUEST_GET_INSTITUTION_LIST',
    RECEIVE_GET_INSTITUTION_LIST: 'RECEIVE_GET_INSTITUTION_LIST',
    RECEIVE_GET_INSTITUTION_LIST_FAIL: 'RECEIVE_GET_INSTITUTION_LIST_FAIL',
}