export const types = {
    ACTIVATE_GAME: 'ACTIVATE_GAME',
    REQUEST_ACTIVATE_GAME: 'REQUEST_ACTIVATE_GAME',
    RECEIVE_ACTIVATE_GAME: 'RECEIVE_ACTIVATE_GAME',
    RECEIVE_ACTIVATE_GAME_FAIL: 'RECEIVE_ACTIVATE_GAME_FAIL',

    START_GAME: 'START_GAME',
    REQUEST_START_GAME: 'REQUEST_START_GAME',
    RECEIVE_START_GAME: 'RECEIVE_START_GAME',
    RECEIVE_START_GAME_FAIL: 'RECEIVE_START_GAME_FAIL',

    JOIN_GAME: 'JOIN_GAME',
    REQUEST_JOIN_GAME: 'REQUEST_JOIN_GAME',
    RECEIVE_JOIN_GAME: 'RECEIVE_JOIN_GAME',
    RECEIVE_JOIN_GAME_FAIL: 'RECEIVE_JOIN_GAME_FAIL',

    SUBMIT_ANSWER: 'SUBMIT_ANSWER',
    REQUEST_SUBMIT_ANSWER: 'REQUEST_SUBMIT_ANSWER',
    RECEIVE_SUBMIT_ANSWER: 'RECEIVE_SUBMIT_ANSWER',
    RECEIVE_SUBMIT_ANSWER_FAIL: 'RECEIVE_SUBMIT_ANSWER_FAIL',

    GET_CURRENT_QUESTION: 'GET_CURRENT_QUESTION',
    REQUEST_GET_CURRENT_QUESTION: 'REQUEST_GET_CURRENT_QUESTION',
    RECEIVE_GET_CURRENT_QUESTION: 'RECEIVE_GET_CURRENT_QUESTION',
    RECEIVE_GET_CURRENT_QUESTION_FAIL: 'RECEIVE_GET_CURRENT_QUESTION_FAIL',

    RECEIVE_GET_CURRENT_QUESTION_TEACHER: 'RECEIVE_GET_CURRENT_QUESTION_TEACHER',
    RECEIVE_GET_LEADERBOARD_PLAYERS_LIST_TEACHER: 'RECEIVE_GET_LEADERBOARD_PLAYERS_LIST_TEACHER',
    END_GAME_TEACHER: 'END_GAME_TEACHER',

    START_CHANNEL: 'START_CHANNEL',
    STOP_CHANNEL: 'STOP_CHANNEL',
    CHANNEL_ON: 'CHANNEL_ON',
    CHANNEL_OFF: 'CHANNEL_OFF',
    GAME_NOT_AVAILABLE: 'GAME_NOT_AVAILABLE',
    END_GAME: 'END_GAME',
    NEW_PLAYER: 'NEW_PLAYER',
    GET_CONNECTED_PLAYERS: 'GET_CONNECTED_PLAYERS',
    SET_LEADERBOARD_FLAG: 'SET_LEADERBOARD_FLAG',
    CANCEL_RECONNECT_FLAG: 'CANCEL_RECONNECT_FLAG',
    SET_WAITING_FLAG: 'SET_WAITING_FLAG',

    GET_LEADERBOARD_PLAYERS_LIST: 'GET_LEADERBOARD_PLAYERS_LIST',
    REQUEST_GET_LEADERBOARD_PLAYERS_LIST: 'REQUEST_GET_LEADERBOARD_PLAYERS_LIST',
    RECEIVE_GET_LEADERBOARD_PLAYERS_LIST: 'RECEIVE_GET_LEADERBOARD_PLAYERS_LIST',
    RECEIVE_GET_LEADERBOARD_PLAYERS_LIST_FAIL: 'RECEIVE_GET_LEADERBOARD_PLAYERS_LIST_FAIL',
};