export const types = {
    ADD_QUESTION: 'ADD_QUESTION',
    REQUEST_ADD_QUESTION: 'REQUEST_ADD_QUESTION',
    RECEIVE_ADD_QUESTION: 'RECEIVE_ADD_QUESTION',
    RECEIVE_ADD_QUESTION_FAIL: 'RECEIVE_ADD_QUESTION_FAIL',

    UPDATE_QUESTION: 'UPDATE_QUESTION',
    REQUEST_UPDATE_QUESTION: 'REQUEST_UPDATE_QUESTION',
    RECEIVE_UPDATE_QUESTION: 'RECEIVE_UPDATE_QUESTION',
    RECEIVE_UPDATE_QUESTION_FAIL: 'RECEIVE_UPDATE_QUESTION_FAIL',

    DELETE_QUESTION: 'DELETE_QUESTION',
    REQUEST_DELETE_QUESTION: 'REQUEST_DELETE_QUESTION',
    RECEIVE_DELETE_QUESTION: 'RECEIVE_DELETE_QUESTION',
    RECEIVE_DELETE_QUESTION_FAIL: 'RECEIVE_DELETE_QUESTION_FAIL',

    GET_QUESTION: 'GET_QUESTION',
    REQUEST_GET_QUESTION: 'REQUEST_GET_QUESTION',
    RECEIVE_GET_QUESTION: 'RECEIVE_GET_QUESTION',
    RECEIVE_GET_QUESTION_FAIL: 'RECEIVE_GET_QUESTION_FAIL',

    GET_QUESTION_LIST: 'GET_QUESTION_LIST',
    REQUEST_GET_QUESTION_LIST: 'REQUEST_GET_QUESTION_LIST',
    RECEIVE_GET_QUESTION_LIST: 'RECEIVE_GET_QUESTION_LIST',
    RECEIVE_GET_QUESTION_LIST_FAIL: 'RECEIVE_GET_QUESTION_LIST_FAIL',

    GET_TEACHER_CATEGORY_LIST: 'GET_TEACHER_CATEGORY_LIST',
    REQUEST_GET_TEACHER_CATEGORY_LIST: 'REQUEST_GET_TEACHER_CATEGORY_LIST',
    RECEIVE_GET_TEACHER_CATEGORY_LIST: 'RECEIVE_GET_TEACHER_CATEGORY_LIST',
    RECEIVE_GET_TEACHER_CATEGORY_LIST_FAIL: 'RECEIVE_GET_TEACHER_CATEGORY_LIST_FAIL',
};