export const types = {
    GET_GROUP_LIST: 'GET_GROUP_LIST',
    REQUEST_GET_GROUP_LIST: 'REQUEST_GET_GROUP_LIST',
    RECEIVE_GET_GROUP_LIST: 'RECEIVE_GET_GROUP_LIST',
    RECEIVE_GET_GROUP_LIST_FAIL: 'RECEIVE_GET_GROUP_LIST_FAIL',
}