export const types = {

    ADD_ACTIVE_QUIZ: 'ADD_ACTIVE_QUIZ',
    REQUEST_ADD_ACTIVE_QUIZ: 'REQUEST_ADD_ACTIVE_QUIZ',
    RECEIVE_ADD_ACTIVE_QUIZ: 'RECEIVE_ADD_ACTIVE_QUIZ',
    RECEIVE_ADD_ACTIVE_QUIZ_FAIL: 'RECEIVE_ADD_ACTIVE_QUIZ_FAIL',

    UPDATE_ACTIVE_QUIZ: 'UPDATE_ACTIVE_QUIZ',
    REQUEST_UPDATE_ACTIVE_QUIZ: 'REQUEST_UPDATE_ACTIVE_QUIZ',
    RECEIVE_UPDATE_ACTIVE_QUIZ: 'RECEIVE_UPDATE_ACTIVE_QUIZ',
    RECEIVE_UPDATE_ACTIVE_QUIZ_FAIL: 'RECEIVE_UPDATE_ACTIVE_QUIZ_FAIL',

    DELETE_ACTIVE_QUIZ: 'DELETE_ACTIVE_QUIZ',
    REQUEST_DELETE_ACTIVE_QUIZ: 'REQUEST_DELETE_ACTIVE_QUIZ',
    RECEIVE_DELETE_ACTIVE_QUIZ: 'RECEIVE_DELETE_ACTIVE_QUIZ',
    RECEIVE_DELETE_ACTIVE_QUIZ_FAIL: 'RECEIVE_DELETE_ACTIVE_QUIZ_FAIL',

    GET_ACTIVE_QUIZ_LIST: 'GET_ACTIVE_QUIZ_LIST',
    REQUEST_GET_ACTIVE_QUIZ_LIST: 'REQUEST_GET_ACTIVE_QUIZ_LIST',
    RECEIVE_GET_ACTIVE_QUIZ_LIST: 'RECEIVE_GET_ACTIVE_QUIZ_LIST',
    RECEIVE_GET_ACTIVE_QUIZ_LIST_FAIL: 'RECEIVE_GET_ACTIVE_QUIZ_LIST_FAIL',

    GET_TEACHER_QUIZ_LIST: 'GET_TEACHER_QUIZ_LIST',
    REQUEST_GET_TEACHER_QUIZ_LIST: 'REQUEST_GET_TEACHER_QUIZ_LIST',
    RECEIVE_GET_TEACHER_QUIZ_LIST: 'RECEIVE_GET_TEACHER_QUIZ_LIST',
    RECEIVE_GET_TEACHER_QUIZ_LIST_FAIL: 'RECEIVE_GET_TEACHER_QUIZ_LIST_FAIL',
};